config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :posts
  draw :turbo

  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users do
        resource :impersonate, module: :user
      end
      namespace :user do
        resources :connected_accounts
      end
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :customers
        resources :charges
        resources :payment_methods
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }
  devise_scope :user do
    get "session/otp", to: "sessions#otp"
  end

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts
  end
  resources :account_invitations

  # Payments
  resources :payment_methods
  resources :subscriptions do
    resource :cancel, module: :subscriptions
    resource :pause, module: :subscriptions
    resource :resume, module: :subscriptions
    collection do
      patch :info
    end
  end
  resources :charges do
    member do
      get :invoice
    end
  end

  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  post :sudo, to: "users/sudo#create"
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: "static#index"
end

app/controllers/admin/pay/subscriptions_controller.rb
module Admin
  class Pay::SubscriptionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Pay::Subscription.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Pay::Subscription.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/subscriptions_controller.rb
module Admin
  class SubscriptionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Subscription.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Subscription.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/subscriptions/cancels_controller.rb
class Subscriptions::CancelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subscription

  def show
  end

  def destroy
    @subscription.cancel

    # Optionally, you can cancel immediately
    # current_account.subscription.cancel_now!

    redirect_to subscriptions_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  private

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id(params[:subscription_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions/pauses_controller.rb
class Subscriptions::PausesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subscription

  def show
  end

  def update
    @subscription.pause
    redirect_to subscriptions_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  private

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id(params[:subscription_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions/resumes_controller.rb
class Subscriptions::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subscription

  def show
  end

  def update
    @subscription.resume
    redirect_to subscriptions_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  private

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id(params[:subscription_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :require_payments_enabled
  before_action :authenticate_user_with_sign_up!
  before_action :require_account
  before_action :require_current_account_admin, except: [:show]
  before_action :set_plan, only: [:new, :create, :update]
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  layout "checkout", only: [:new, :create]

  def index
    @payment_processor = current_account.payment_processor
    @subscriptions = current_account.subscriptions.active.order(created_at: :asc).includes([:customer])
  end

  def show
    redirect_to edit_subscription_path(@subscription)
  end

  def new
    if Jumpstart.config.stripe? && @plan.has_trial?
      @setup_intent = current_account.payment_processor&.stripe? ? current_account.payment_processor.create_setup_intent : Stripe::SetupIntent.create
    end
  end

  def create
    payment_processor = params[:processor] ? current_account.set_payment_processor(params[:processor]) : current_account.payment_processor
    payment_processor.payment_method_token = params[:payment_method_token]
    payment_processor.subscribe(
      plan: @plan.id_for_processor(payment_processor.processor),
      trial_period_days: @plan.trial_period_days
    )
    redirect_to root_path, notice: t(".created")
  rescue Pay::ActionRequired => e
    redirect_to pay.payment_path(e.payment.id)
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :new, status: :unprocessable_entity
  end

  def edit
    # Include current plan even if hidden
    @current_plan = @subscription.plan

    plans = Plan.visible.sorted.or(Plan.where(id: @current_plan.id))
    @monthly_plans = plans.select(&:monthly?)
    @yearly_plans = plans.select(&:yearly?)
  end

  def update
    @subscription.swap @plan.id_for_processor(current_account.payment_processor.processor)
    redirect_to subscriptions_path, notice: t(".success")
  rescue Pay::Error => e
    edit # Reload plans
    flash[:alert] = e.message
    render :edit, status: :unprocessable_entity
  end

  def resume
    current_account.payment_processor.subscription.resume
    redirect_to subscriptions_path, notice: t(".resumed")
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  def pause
    current_account.payment_processor.subscription.pause
    redirect_to subscriptions_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show
  end

  def destroy
    @subscription.cancel

    # Optionally, you can cancel immediately
    # @subscription.cancel_now!

    redirect_to subscriptions_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  def info
    current_account.update(info_params)
    redirect_to subscriptions_path, notice: t(".info_updated")
  end

  private

  def info_params
    params.require(:account).permit(:extra_billing_info)
  end

  def require_account
    redirect_to new_user_registration_path unless current_account
  end

  def require_payments_enabled
    return if Jumpstart.config.payments_enabled?
    flash[:alert] = "Jumpstart must be configured for payments before you can manage subscriptions."
    redirect_back(fallback_location: root_path)
  end

  def set_plan
    @plan = Plan.without_free.find(params[:plan])
  rescue ActiveRecord::RecordNotFound
    redirect_to pricing_path
  end

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id(params[:id])
    redirect_to subscriptions_path if @subscription.nil?
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def braintree_env
    Rails.env.production? ? "production" : "sandbox"
  end

  def payment_method_details(object)
    case object.payment_method_type
    when "paypal"
      object.email || "PayPal"
    when "card"
      "#{object.brand.titleize} ending in #{object.last4}"
    end
  end

  def show_payment_processor?(processor_name, plan: nil)
    return unless Jumpstart.config.payment_processors.include?(processor_name)

    # Make sure we have a Plan ID for the payment processor
    return false if plan && !plan.id_for_processor(processor_name).present?

    # If a user has active subscriptions, only let them use that payment processor for new payments
    # Also show if user is on the fake processor (for trial)
    if current_account.subscriptions.active.any?
      ["fake_processor", processor_name.to_s].include?(current_account.payment_processor.processor)

    # Otherwise show all options
    else
      true
    end
  end

  # Paddle can only update payment method when subscribed
  # Only works with active or paused subscriptions.
  # Cancelled subscriptions are permanent and cannot be updated.
  def show_paddle_payment_method_form?(payment_processor)
    return false unless payment_processor&.paddle?
    (subscription = payment_processor.subscription) && (subscription.active? || subscription.paused?)
  end
end

app/views/subscriptions/_billing_info.html.erb
<h5 class="text-gray-700 font-semibold my-4 border-b border-gray-200 pb-2"><%= t(".extra_billing_info") %></h5>

<div class="mb-8 flex gap-8" data-controller="toggle">
  <div class="flex-1">
    <div class="text-gray-700 mt-2"><%= t ".additional_information" %></div>

    <%= form_with model: current_account, url: info_subscriptions_path, html: { class: "hidden mt-4 max-w-lg", data: { toggle_target: "toggleable" }} do |f| %>
      <div class="form-group">
        <%= f.label :extra_billing_info %>
        <%= f.text_area :extra_billing_info, class: "form-control", placeholder: true %>
      </div>

      <div class="form-group">
        <%= f.button t(".save_info"), class: "btn btn-primary", data: { disable_with: disable_with(t(".saving"))} %>
      </div>
    <% end %>
  </div>

  <div>
    <%= link_to t(".add_info"), "#", class: "btn btn-light-gray", data: { action: "click->toggle#toggle" } %>
  </div>
</div>

<% if current_account.extra_billing_info? %>
  <blockquote class="mt-4 mb-8 text-gray-600 border-l-4 border-gray-200 px-4 font-mono text-sm">
    <%= current_account.extra_billing_info %>
  </blockquote>
<% end %>

app/views/subscriptions/_cancel.html.erb
<% if (subscription = current_account.payment_processor&.subscription) && !subscription.cancelled? %>
  <hr class="border-b border-gray-200 my-8" />
  <h3><%= t ".title" %></h3>
  <div class="flex">
    <div class="flex-1 mt-2 text-gray-700">
      <div class="font-bold"><%= t ".description", product: Jumpstart.config.application_name %></div>
      <div><%= t ".help_html", link: mail_to(Jumpstart.config.support_email, t(".contact_us"), subject: t(".subject", product: Jumpstart.config.application_name), class: "underline text-blue-600") %></div>
    </div>

    <div>
      <%= link_to t(".button"), subscription_url, method: :delete, class: "btn btn-link text-gray-700", data: { confirm: t("are_you_sure"), disable_with: disable_with(t(".cancelling")) } %>
    </div>
  </div>
<% end %>

app/views/subscriptions/_charges.html.erb
<h5 class="text-gray-700 font-semibold my-4 border-b border-gray-200 pb-2"><%= t(".title") %></h5>

<% if current_account.charges.sorted.any? %>
  <table class="w-full text-sm">
    <thead class="bg-gray-100">
      <tr>
        <th class="p-3 uppercase text-left text-xs text-gray-500"><%= t ".date" %></th>
        <th class="hidden table-cell p-3 uppercase text-left text-xs text-gray-500"><%= t ".payment_method" %></th>
        <th class="p-3 uppercase text-left text-xs text-gray-500"><%= t ".amount" %></th>
        <th class="p-3 uppercase text-center text-xs text-gray-500"><%= t ".receipt" %></th>
      </tr>
    </thead>

    <tbody>
      <% current_account.charges.sorted.each do |charge| %>
        <tr class="group border-t border-gray-200 hover:bg-gray-50">
          <td class="p-3 font-medium">
            <%= link_to invoice_charge_path(charge, format: :pdf), target: :_blank do %>
              <%= charge.created_at.strftime("%B %e, %Y") %>
              <svg xmlns="http://www.w3.org/2000/svg" class="inline-block h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z" />
                <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z" />
              </svg>
            <% end %>
          </td>
          <td class="hidden table-cell p-3">
            <i class="fab fa-cc-<%= charge.brand.downcase %> text-gray-700"></i>
            <%= payment_method_details(charge) %>
          </td>
          <td class="p-3"><%= charge.amount_with_currency %></td>
          <td class="p-3 text-center text-sm">
            <% if charge.paddle_receipt_url %>
              <%= link_to t(".view"), charge.paddle_receipt_url, target: :_blank %>
            <% else %>
              <%= link_to charge_path(charge, format: :pdf), target: :_blank do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="inline-block text-gray-500 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                </svg>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <div class="text-gray-700"><%= t(".empty") %></div>
<% end %>

app/views/subscriptions/_pause.html.erb
<%# Pause is only available with Paddle subscriptions %>
<% if !subscription.paused? %>
  <hr class="border-b border-gray-200 my-8" />
  <h3><%= t ".pause.title" %></h3>
  <div class="flex">
    <div class="flex-1 mt-2 text-gray-700">
      <div class="font-bold"><%= t ".pause.description" %></div>
      <div><%= t ".pause.note" %></div>
    </div>

    <div>
      <%= form_for current_account, url: pause_subscription_url, method: :patch do |f| %>
        <%= f.button t(".pause.button"), class: "btn btn-link text-gray-700", data: { disable_with: disable_with(t(".pause.pausing")) } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/subscriptions/_payment_method.html.erb
<h5 class="text-gray-700 font-semibold my-4 border-b border-gray-200 pb-2"><%= t(".payment_method") %></h5>

<div class="mb-8 lg:flex lg:gap-8">
  <div class="flex-1 my-4">
    <% if (payment_method = payment_processor&.default_payment_method) %>
      <i class="fab fa-cc-<%= payment_method.brand.downcase %> text-gray-700"></i>
      <%= payment_method_details(payment_method) %>
    <% else %>
      <p class="text-gray-700"><%= t ".no_payment_method" %></p>
    <% end %>
  </div>

  <div>
    <%= link_to t(".update_payment_method"), new_payment_method_path, class: "btn btn-light-gray" unless payment_processor.paddle? && !show_paddle_payment_method_form?(payment_processor) %>
  </div>
</div>

app/views/subscriptions/_plan.html.erb
<div class="lg:w-1/3 w-full p-8 border border-gray-200 m-4 rounded-lg bg-white">
  <h4 class="mb-4"><%= plan.name %></h4>

  <div class="mb-4">
    <span class="text-5xl font-bold"><%= plan.amount_with_currency(strip_insignificant_zeros: true) %></span>
    <span class="text-lg text-gray-500 font-medium">/ <%= plan.interval %></span>
  </div>

  <p class="mb-4 text-gray-500"><%= plan.description %></p>

  <div class="mb-8">
    <% plan.features.each do |plan_feature| %>
      <div class="flex mb-2 text-gray-500">
        <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 mr-2 text-blue-500 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
        </svg>
        <div><%= plan_feature %></div>
      </div>
    <% end %>
  </div>

  <%# Yield for custom actions at the bottom %>
  <%= yield %>
</div>

app/views/subscriptions/_subscription.html.erb
<%= tag.div class: "mb-8 lg:flex lg:gap-8", id: dom_id(subscription) do %>
  <% if subscription.generic_trial? %>
    <div>
      <%= badge t(".free_trial"), class: "mb-1" %>
      <div><%= t(".free_trial_ends", date: l(subscription.trial_ends_at.to_date, format: :long)) %></div>
    </div>

  <% else %>
    <div class="flex-1">
      <% if subscription.canceled? %>
        <%= badge t(".canceled"), class: "mb-1" %>
      <% elsif subscription.incomplete? %>
        <%= badge t(".incomplete"), class: "mb-1" %>
      <% end %>

      <h4><%= subscription.plan.name %></h4>
      <div class="mb-2 text-lg"><%= subscription.amount_with_currency %> per <%= subscription.plan.interval %></div>

      <% if subscription.quantity > 1 %>
        <div><%= t(".quantity", quantity: subscription.quantity, price: subscription.plan.amount_with_currency) %></div>
      <% end %>

      <% if subscription.on_trial? && subscription.canceled? %>
        <div><%= t(".canceled_on_trial", date: l(subscription.trial_ends_at.to_date, format: :long)) %></div>
      <% elsif subscription.on_trial? %>
        <div><%= t(".trial", date: l(subscription.trial_ends_at.to_date, format: :long)) %></div>
      <% elsif subscription.on_grace_period? %>
        <div class="flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="inline-block fill-current text-gray-400 h-4 w-4 mr-2" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
          </svg>
          <% if subscription.ends_at? %>
            <%= t(".ends_at", date: l(subscription.ends_at.to_date, format: :long)) %>
          <% elsif subscription.paddle_paused_from %>
            <%= t(".paused_at", date: l(subscription.paddle_paused_from.to_date, format: :long)) %>
          <% end %>
        </div>
      <% elsif subscription.paused? %>
        <div><%= t(".paused") %></div>
      <% end %>
    </div>

    <div class="mt-2 flex flex-col gap-2 text-center">
      <% if subscription.on_grace_period? && !subscription.paddle? %>
        <%# Cancelled paddle subscriptions cannot be resumed %>
        <%= link_to t(".resume"), subscription_resume_path(subscription), class: "btn btn-primary" %>
      <% elsif subscription.paused? %>
        <%= link_to t(".resume"), subscription_resume_path(subscription), class: "btn btn-primary" %>
        <%= link_to t(".cancel_plan"), subscription_cancel_path(subscription), class: "btn btn-light-gray" %>
      <% elsif subscription.active? %>
        <%= link_to t(".change_plan"), edit_subscription_path(subscription), class: "btn btn-primary" %>
        <%= link_to t(".pause"), subscription_pause_path(subscription), class: "btn btn-light-gray" if subscription.paddle? || subscription.fake_processor? %>
        <%= link_to t(".cancel_plan"), subscription_cancel_path(subscription), class: "btn btn-light-gray" %>
      <% elsif subscription.incomplete? %>
        <%= link_to t(".confirm_payment"), pay.payment_path(subscription.latest_payment.id), class: "btn btn-primary" %>
      <% elsif subscription.past_due? %>
        Past Due
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/subscriptions/edit.html.erb
<% if @subscription.on_trial? %>
  <div class="flex justify-center items-center bg-orange-200 text-orange-600 text-sm font-bold px-4 py-3 mb-4" role="alert">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
    <p><%= t(".trial_ends", days: time_ago_in_words(@subscription.trial_ends_at)) %></p>
  </div>
<% end %>

<div class="container m-auto my-10">
  <div class="flex flex-wrap justify-center">
    <div class="text-center">
      <h1><%= t(".title") %></h1>
      <p class="mt-2 text-xl text-gray-500"><%= t(".description") %></p>
    </div>
  </div>

  <div data-controller="pricing" class="sm:flex flex-wrap items-center justify-center">
    <div data-pricing-target="toggle" class="relative self-center my-8 bg-gray-200 rounded-full p-0.5 flex sm:mt-8">
      <button type="button" data-action="click->pricing#switch" data-pricing-target="frequency" data-frequency="monthly" class="relative w-1/2 bg-white border-gray-200 rounded-full py-2 text-sm font-medium text-gray-700 whitespace-nowrap focus:outline-none focus:z-10 sm:w-auto sm:px-8">Monthly</button>
      <button type="button" data-action="click->pricing#switch" data-pricing-target="frequency" data-frequency="yearly" class="ml-0.5 relative w-1/2 border border-transparent rounded-full py-2 text-sm font-medium text-gray-700 whitespace-nowrap focus:outline-none focus:z-10 sm:w-auto sm:px-8">Yearly</button>
    </div>

    <div class="w-full lg:px-0 px-2">
      <div data-pricing-target="plans" data-frequency="monthly" class="flex flex-wrap items-center justify-center -mx-4">
        <% @monthly_plans.each do |plan| %>
          <%= render layout: "subscriptions/plan", locals: { plan: plan } do %>
            <% if @subscription.plan == plan %>
              <div class="btn btn-light-gray btn-block"><%= t(".current_plan") %></div>
            <% else %>
              <%= form_with url: subscription_url, method: :patch do |f| %>
                <%= f.hidden_field :plan, value: plan.id %>
                <%= f.button t(".change_plan"), class: "btn btn-tertiary btn-block", data: { disable_with: t(".processing") } %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div data-pricing-target="plans" data-frequency="yearly" class="hidden flex-wrap items-center justify-center -mx-4">
        <% @yearly_plans.each do |plan| %>
          <%= render layout: "subscriptions/plan", locals: { plan: plan } do %>
            <% if @subscription.plan == plan %>
              <div class="btn btn-light-gray btn-block"><%= t(".current_plan") %></div>
            <% else %>
              <%= form_with url: subscription_url, method: :patch do |f| %>
                <%= f.hidden_field :plan, value: plan.id %>
                <%= f.button t(".change_plan"), class: "btn btn-tertiary btn-block", data: { disable_with: t(".processing") } %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/subscriptions/index.html.erb
<div class="flex flex-wrap my-4 lg:px-4">
  <div class="w-full mb-4 lg:w-1/4 lg:p-4">
    <%= render partial: "shared/account_navbar" %>
  </div>

  <div class="w-full lg:w-3/4 lg:p-4">
    <div class="lg:p-10 p-4 bg-white rounded-lg border border-gray-200">
      <h1 class="h3 mb-2"><%= t(".title") %></h1>

      <% if account_admin?(current_account, current_user) %>
        <h5 class="text-gray-700 font-semibold my-4 border-b border-gray-200 pb-2"><%= t(".subscriptions") %></h5>
        <% if @subscriptions.any? %>
          <%= render partial: "subscriptions/subscription", collection: @subscriptions %>
        <% else %>
          <div class="flex">
            <div class="flex-1 mt-2 text-gray-700"><%= t ".not_subscribed" %></div>
            <div><%= link_to t(".choose_plan"), pricing_path, class: "btn btn-primary" %></div>
          </div>
        <% end %>

        <% if @payment_processor %>
          <%= render "subscriptions/payment_method", payment_processor: @payment_processor %>
        <% end %>

        <%# Paddle: Extra payment details live in Paddle, not our app %>
        <% unless @payment_processor&.paddle? %>
          <%= render partial: "subscriptions/billing_info" %>
        <% end %>

        <%= render partial: "subscriptions/charges" %>
      <% else %>
        <p><%= t(".contact_admin", account: current_account.name) %></p>
      <% end %>
    </div>
  </div>
</div>